-- 0002_core_occurrences.sql  —  TODO (you build this)
-- ===========================================================================
-- WHAT: The precise, PRIVATE `occurrences` table (full-precision geometry in
--       EPSG:27700, the original grid ref + derived precision, dates, and the
--       BRERC fields `recorder1` (PII) and `bliss`). Plus a small `public_config`
--       table (baseline + review-default resolutions) that tunes generalisation.
-- WHY:  Everything else reads FROM here (via the gate). Get the columns, the
--       geometry SRID, and the CHECK constraints right first.
--
-- BUILD IT: Learning Guide -> 02-database-and-the-gate.md (section 2 + public_config).
--   Answer Key: brerc-public-dashboard/db/migrations/0002_core_occurrences.sql
-- ACCEPTANCE: `make db-migrate` runs clean; `\d occurrences` shows a
--   geometry(Point,27700) column plus the recorder1 / bliss fields.
--
-- Intentionally EMPTY (a no-op migration) until you implement it. Replace this
-- whole comment block with your SQL. Mark guessed columns "[assumed]".
-- ===========================================================================
