-- 0004_public_occurrences_view.sql  —  TODO (THE GATE — most important file)
-- ===========================================================================
-- WHAT: The `public_occurrences` view + helpers (`generalise_point`,
--       `en_to_gridref`). The ONE gate every public path reads. It must:
--         * blur each point to the CENTRE of its grid cell (floor arithmetic in
--           EPSG:27700 metres),
--         * pick the resolution as the COARSEST of {baseline, the record's own
--           precision, any sensitive-list requirement / review default},
--         * drop recorder PII and the precise columns entirely,
--         * omit blocked taxa and rows with no geometry (FAIL CLOSED).
-- WHY:  Blur BEFORE data leaves the server — you can't un-send what the browser
--       already has. This file is the whole security model.
--
-- BUILD IT: Learning Guide -> 02-database-and-the-gate.md (section 4 — slowly).
--   Answer Key: brerc-public-dashboard/db/migrations/0004_public_occurrences_view.sql
-- ACCEPTANCE: with 0006 (roles) + a seed in place, `make gate-test` passes.
--
-- Take your time here. Intentionally EMPTY until you implement it.
-- ===========================================================================
