-- 0006_roles.sql  —  TODO (you build this)
-- ===========================================================================
-- WHAT: The READ-ONLY role `brerc_readonly` that Martin + FastAPI connect as.
--       REVOKE everything first, then GRANT SELECT on `public_occurrences` and
--       EXECUTE on the tile function ONLY; deny the precise `occurrences` table.
--       Set default_transaction_read_only + a statement_timeout on the role.
-- WHY:  Defence in depth — even buggy app code can't reach precise data if the
--       role literally cannot read the table.
--
-- BUILD IT: Learning Guide -> 02-database-and-the-gate.md (section 5).
--   Answer Key: brerc-public-dashboard/db/migrations/0006_roles.sql
-- ACCEPTANCE: gate-test check (7) passes. (The Makefile passes the password via
--   -v readonly_password="$BRERC_READONLY_PASSWORD".)
--
-- Intentionally EMPTY until you implement it.
-- ===========================================================================
