-- 0010_data_quality_views.sql  (INTERNAL)  —  TODO (you build this)
-- ===========================================================================
-- WHAT: Data-quality + content views over the PRECISE `occurrences` table for
--   the staff dashboard: internal_summary, internal_data_quality (one row per
--   record+issue), internal_dq_summary, internal_duplicate_groups, and
--   breakdowns by year / dataset (BLISS) / recorder (Recorder1).
-- WHY:  Secondary deliverable. Internal tier only (it exposes PII) — see 0011.
--
-- BUILD IT: Learning Guide -> 07-internal-dashboard.md (section 3).
--   Answer Key: brerc-public-dashboard/db/internal/0010_data_quality_views.sql
-- Intentionally EMPTY until you implement it.
-- ===========================================================================
