-- 0011_internal_role.sql  (INTERNAL)  —  TODO (you build this)
-- ===========================================================================
-- WHAT: The read-only role `brerc_internal_ro` that MAY read the precise table +
--   recorder names (access-controlled, operational need). Read-only; grant SELECT
--   on occurrences + the internal_* views; never expose to the public proxy.
--
-- BUILD IT: Learning Guide -> 07-internal-dashboard.md (section 2).
--   Answer Key: brerc-public-dashboard/db/internal/0011_internal_role.sql
-- Intentionally EMPTY until you implement it.
-- ===========================================================================
