import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { GroupBreakdown } from "./OverviewPage";

describe("GroupBreakdown", () => {
  it("says the breakdown is unavailable, and why, when the release publishes no groups", () => {
    // This is the live case. The publication store CHECK-constrains taxon_group to NULL
    // until BRERC approves a vocabulary, so /api/summary returns an empty list. The
    // mid-review prototype filled this panel with numbers generated by Math.sin(); a
    // public dashboard for a records centre must not do that.
    render(<GroupBreakdown groups={[]} />);
    expect(screen.getByText(/Not available in this release/i)).toBeInTheDocument();
    expect(screen.getByText(/approve the vocabulary/i)).toBeInTheDocument();
    // No bar is drawn at all — not a zero-length one, which would read as "no records".
    expect(document.querySelectorAll(".hbar-fill")).toHaveLength(0);
  });

  it("states every value as text, never only as a bar length", () => {
    // WCAG 1.4.1: the bar illustrates the number, it is not the only way to read it.
    render(<GroupBreakdown groups={[{ group: "Reptile", count: 300 }, { group: "Bird", count: 100 }]} />);
    expect(screen.getByText(/300 · 75\.0%/)).toBeInTheDocument();
    expect(screen.getByText(/100 · 25\.0%/)).toBeInTheDocument();
  });

  it("scales bars against the largest group and percentages against the total", () => {
    render(<GroupBreakdown groups={[{ group: "Reptile", count: 300 }, { group: "Bird", count: 100 }]} />);
    const fills = [...document.querySelectorAll<HTMLElement>(".hbar-fill")];
    expect(fills.map((el) => el.style.width)).toEqual(["100%", `${(100 / 300) * 100}%`]);
    expect(screen.getByText(/75\.0%/)).toBeInTheDocument();
    expect(screen.getByText(/25\.0%/)).toBeInTheDocument();
  });

  it("groups the numbers with thousands separators", () => {
    render(<GroupBreakdown groups={[{ group: "Plant", count: 1234567 }]} />);
    expect(screen.getByText(/1,234,567/)).toBeInTheDocument();
  });

  it("does not divide by zero when every group is empty", () => {
    // A release could legitimately publish groups with no records in them yet.
    render(<GroupBreakdown groups={[{ group: "Insect", count: 0 }]} />);
    const width = document.querySelector<HTMLElement>(".hbar-fill")?.style.width ?? "";
    expect(width).not.toContain("NaN");
    expect(screen.queryByText(/NaN/)).toBeNull();
  });
});
